#!/usr/bin/env bash

# fzf with default opts
fzf () {
	FZF_DEFAULT_OPTS='--no-bold --color=fg:7,fg+:3,bg:-1,bg+:-1,hl:6,hl+:6,prompt:8,pointer:3,marker:2' command fzf
}

# display and prompt for wifi with fzf
print_wifi () {
	nmcli --terse device wifi list | while IFS=: read -r _ name _ _ _ _ str security _; do
		printf '%s\t%s\t%s\n' "$name" "$str" "$security"
	done
}
chosen_wifi=$(print_wifi | fzf)

# fail fast if no wifi is chosen
[[ -z "$chosen_wifi" ]] && exit 1

IFS=$'\t' read -r chosen_ssid _ security <<< "$chosen_wifi"

# check for existing NetworkManager connection
if nmcli --terse connection show "$chosen_ssid" &>/dev/null; then
	>&2 echo "Activating existing profile for $chosen_ssid..."
	notify-exit nmcli connection up "$chosen_ssid"
else
	# check if password is necessary
	if [[ $security =~ "WPA" ]]; then
		read -r -p "Password: " password

		>&2 echo "Connecting to $chosen_ssid..."
		notify-exit nmcli device wifi connect "$chosen_ssid" password "$password"
	else
		>&2 echo "Connecting to $chosen_ssid..."
		notify-exit nmcli device wifi connect "$chosen_ssid"
	fi
fi
