#!/usr/bin/env bash

cd "$HOME/.password-store" || exit 1
pass_name=$(fd --type file --exec echo '{.}' | rofi -dmenu -i -p "pass")

[[ -n $pass_name ]] || exit 1

length=$(zenity --entry --entry-text=20 \
	--text="Password length for $pass_name:")
[[ -n $length ]] || exit 1
if pass generate -n -c "$pass_name" "$length"; then
	notify-send --urgency=normal "$pass_name" \
		"New password generated for $pass_name. Copied to clipboard!"
else
	notify-send --urgency=normal "$pass_name" \
		"Failed to generate password for $pass_name."
fi
