#!/usr/bin/env bash

# assign unique dunst notification ID
id=8000

if pkill xautolock; then
	dunstify -r "$id" -i none -u low ' Autolock off'
else
	xautolock -time 15 -locker lockscreen & disown
	dunstify -r "$id" -u low ' Autolock on'
fi
