#!/usr/bin/env bash

sleep .2 # race condition with caps :(

# assign unique dunst notification ID
id=9000

value="$(xset q | awk '/LED mask/ { print $NF }')"
if (( 0x$value & 0x1 )); then
	dunstify -a locknotify -i none -r "$id" --urgency=low 'Caps on'
else
	dunstify -a locknotify -i none -r "$id" --urgency=low 'Caps off'
fi
