#!/usr/bin/env bash

# Indicator is styled c/o i3lock-color
#
# Ring is made smaller and thinner. It is also positioned in the bottom right corner.
#
# Ring color is picked from Doors of Durin image itself (for an almost-glowing white).
#
# Other indicator colors are picked from Material Design spec instead of Base 16 Eighties,
# since the low-contrast Eighties colors are harder to distinguish on a small, thin ring.

i3lock --image="$HOME/Pictures/Wallpapers/Doors of Durin.png" \
	--scale \
	--radius 12 \
	--ring-width 3 \
	--ring-color=f3fcf7ff \
	--ringver-color=29b6f6ff \
	--insidever-color=00000000 \
	--ringwrong-color=ef5350ff \
	--insidewrong-color=00000000 \
	--keyhl-color=4caf50ff \
	--bshl-color=ef5350ff \
	--separator-color=00000000 \
	--ind-pos='w - 25: h - 25' \
	--verif-text= \
	--wrong-text= \
	--noinput-text= \
	--lock-text= \
	--lockfailed-text=
