#!/usr/bin/env bash

conf_path="$HOME/.config/locktoggle"
lockdir=lock
# assign unique dunst notification ID
id=8000

[[ -d "$conf_path" ]] || mkdir -p "$conf_path"

# use lockdir to infer toggle state
if mkdir "$conf_path/$lockdir"; then
	xset s 900 +dpms
	dunstify -r "$id" -u low ' Autolock on'
else
	xset s off -dpms
	dunstify -r "$id" -i none -u low ' Autolock off'
	rmdir "$conf_path/$lockdir"
fi
