#!/usr/bin/env bash

# assign unique dunst notification ID
id=8001

follow=0
skip=0
while (( $# )); do
	case $1 in
		--follow|-F)
			follow=1
			;;
		--skip-first)
			skip=1
			;;
	esac
	shift
done

playerctl_format=$'{{ default(playerName, "unknown") }}'\
$'\t{{ status }}'\
$'\t{{ default(title, "Unknown Media") }}'\
$'\t{{ default(artist, "null") }}'\
$'\t{{ default(album, "null") }}'\
$'\t{{ default(mpris:artUrl, "null") }}'

# helper function with extra args
playerctl () {
	local control_args=()
	# pass down --follow
	(( follow )) && control_args+=(--follow)
	# declare --format
	control_args+=(--format "$playerctl_format")

	command playerctl "${control_args[@]}" "$@"
}

# keep an assoc array of nice names
declare -A player_names=( \
	[cmus]='cmus' \
	[mpd]='MPD' \
	[vlc]='VLC' \
)

playerctl metadata | while IFS=$'\t' read -r player status title artist album art_url; do
	# check for skip_first
	if (( skip )); then
		skip=0
		continue
	fi

	# build notification
	# title
	player_name="${player_names[$player]}"
	[[ -z $player_name ]] && player_name="${player^*}"
	notif_title="Media: $player_name"

	# body
	notif_body="$status <b>$title</b>"
	# conditional lines
	[[ $artist != null ]] && notif_body+=$"\nby <i>$artist</i>"
	[[ $album != null ]] && notif_body+=$"\nfrom <i>$album</i>"

	# image
	notif_image=
	if [[ $art_url != null ]] && [[ $art_url =~ ^file:// ]]; then
		notif_image=${art_url#file://}
	fi

	# build dunstify command
	dunstify_args=()
	# conditional icon
	[[ -n $notif_image ]] && dunstify_args+=(-I "$notif_image")
	# rest of args
	dunstify_args+=(-a playerctl-notify -r "$id" "$notif_title" "$notif_body")

	dunstify "${dunstify_args[@]}"
done
