#!/usr/bin/env bash

# Usage:
# rnotify user@host title message

connection_string=$1
shift

# build command with quotes, since ssh will pass the argument directly
notify_send_command=(notify-send)
for arg in "$@"; do
	notify_send_command+=("'$arg'")
done

# make use of ssh's [command [argument ...]] syntax
ssh "$connection_string" "${notify_send_command[@]}"
