#!/usr/bin/env bash

progress () {
	zenity --progress --title "$1" --text "$2" --pulsate --no-cancel --auto-close
}

mapfile -t wifi_list < <(nmcli --terse --fields SECURITY,BARS,SSID device wifi list) \
	> >(progress Wifi Scanning...)

iter_wifi () {
	local i wifi security bars ssid
	for i in "${!wifi_list[@]}"; do
		wifi="${wifi_list[$i]}"
		IFS=: read -r security bars ssid <<< "$wifi"
		printf '%s\t%s\t%s\n' "$((i + 1))" "${ssid/\\:/:}" "$bars"
	done
}
print_wifi () {
	iter_wifi | column -t -s $'\t'
}

read -r idx _ < <(print_wifi | rofi -dmenu -i -p wifi)
# fail fast if rofi was canceled
[[ -z "$idx" ]] && exit 1

IFS=: read -r security _ ssid <<< "${wifi_list[$((idx - 1))]}"
ssid="${ssid/\\:/:}" # unescape : in SSID

# check for existing NetworkManager connection
if nmcli --terse connection show "$ssid" &>/dev/null; then
	notify-exit nmcli connection up "$ssid" |
		progress Wifi "Activating existing profile for $ssid..."
else
	# check if password is necessary
	if [[ $security =~ "WPA" ]]; then
		password=$(zenity --entry --title='Authentication' \
			--text="Password for $ssid:" --hide-text) || exit 1

		notify-exit nmcli device wifi connect "$ssid" password "$password" |
			progress Wifi "Connecting to $ssid..."
	else
		notify-exit nmcli device wifi connect "$ssid" | 
			progress Wifi "Connecting to $ssid..."
	fi
fi
