#!/usr/bin/env bash

# Original author: carnager (see https://github.com/carnager/clerk/issues/39)
# Modified for my tastes

menu=$(mpc playlist -f '%position%: %artist% - %title%' |
	rofi -dmenu -i -p 'music') || exit
IFS=: read -r id rest <<< "$menu"
mpc play "$id"
