#!/usr/bin/env bash

temp_profile=

clean_temp () {
	[[ -d "$temp_profile" ]] && rm -r "$temp_profile"
}

trap clean_temp EXIT
temp_profile=$(mktemp -d --tmpdir wildfirefox.XXXXXXXXXX)

firefox --profile "$temp_profile"
