#!/usr/bin/env bash

log () {
	printf '%s\n' "$*" >&2
}
die () {
	log "$@"
	exit 1
}

engines_dir="$HOME/.local/share/search/engines"

cd "$engines_dir" || die "Cannot cd to engines_dir: $engines_dir"

# save line, in case we actually need it entirely for default search
IFS= read -r line < <(fd | rofi -dmenu -p search)
[[ -n $line ]] || exit

read -r engine args <<< "$line"
# special case: default search
if ! [[ -e $engine ]]; then
	engine=d
	args="$line"
fi

# i3: ensure tmux: browse window exists and focus it
if i3-msg -t get_tree | grep -q 'tmux: browse'; then
	i3-msg '[title="tmux: browse"] focus'
else
	i3-msg 'workspace "3:"'
	st -e tmux attach -t browse &>/dev/null & disown
	sleep 0.1
fi

# tmux: ensure we're on search window
# NOTE: assumes only a single tmux: browse client (operates on first found)
IFS= read -r client < <(tmux list-clients -t browse -F '#{client_name}')
# NOTE: assumes exact browse layout (operates on pane 5)
tmux switch-client -c "$client" -t %5

# tmux: check if we're running another browser
# NOTE: assumes exact browse layout (operates on pane 5)
IFS=: read -r pane command < <(tmux list-panes -t browse -F '#D:#{pane_current_command}' | grep %5)
# TODO: how to save? i don't want to close all the time
[[ $command = w3m ]] && tmux send-keys -t %5 qy

tmux send-keys -t %5 "sr '$engine' '$args'" Enter
