#!/usr/bin/env bash

# TODO: notice all my engines just declare url="..." then unconditionally do exec w3m "$url"
# i should move them all into a function with an assoc array

engines_dir="$HOME/.local/share/search/engines"
engine="$1"
shift
args=("$@")
script="$engines_dir/$engine"

die () {
	printf '%s\n' "$*" >&2
	exit 1
}

[[ -e "$script" ]] || die "No search engine configured for: $engine"

exec "$script" "${args[@]}"
